using System.Threading.Tasks;

namespace SmokingCessation.Application.Service.Interfaces
{
    public interface IDeepSeekService
    {
        /// <summary>
        /// Generates advice text for quitting smoking based on user and quit plan information.
        /// </summary>
        /// <param name="prompt">The prompt or context to send to DeepSeek.</param>
        /// <returns>Advice text generated by DeepSeek.</returns>
       
        Task<string> GenerateAdviceByOpenRouterAsync(string prompt);



    }
} 